#!/usr/bin/env node

import {
  mkdir,
  readFile,
  readdir,
  writeFile,
} from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const generatedNotice =
  "<!-- Generated by adapters/generate.mjs from canonical guidance. Do not edit. -->";

/**
 * Guidance is generated per format, not per client, because a client only ever
 * needs one of these shapes: Codex and Claude both read plain markdown, and
 * Cursor needs the always-apply rule frontmatter around the same body.
 */
export function buildGuidance({ format, guidance }) {
  const canonicalGuidance = guidance.trimEnd();

  if (format === "cursor-rule") {
    return [
      "---",
      "description: Personal agent guidance",
      "alwaysApply: true",
      "---",
      "",
      generatedNotice,
      "",
      canonicalGuidance,
      "",
    ].join("\n");
  }

  if (format === "markdown") {
    return [generatedNotice, "", canonicalGuidance, ""].join("\n");
  }

  throw new Error(`Unknown guidance format: ${format}`);
}

export async function generateAdapters({
  check = false,
  root = repositoryRoot,
} = {}) {
  const manifest = JSON.parse(
    await readFile(join(root, "manifest.json"), "utf8"),
  );
  const guidance = await readFile(join(root, manifest.core.guidance), "utf8");
  const outputs = Object.values(manifest.clients).map((client) => ({
    content: buildGuidance({ format: client.guidance.format, guidance }),
    path: client.guidance.source,
  }));

  if (check) {
    const drift = [];

    for (const output of outputs) {
      let existing;

      try {
        existing = await readFile(join(root, output.path), "utf8");
      } catch (error) {
        if (error.code !== "ENOENT") {
          throw error;
        }
      }

      if (existing !== output.content) {
        drift.push(output.path);
      }
    }

    return { drift };
  }

  for (const output of outputs) {
    const outputPath = join(root, output.path);
    await mkdir(dirname(outputPath), { recursive: true });
    await writeFile(outputPath, output.content);
  }

  return { drift: [] };
}

export async function readSkills(skillsRoot) {
  const entries = await readdir(skillsRoot, { withFileTypes: true });
  const skills = [];
  const names = new Set();

  for (const entry of entries) {
    if (!entry.isDirectory()) {
      continue;
    }

    const skillRoot = join(skillsRoot, entry.name);
    const skillPath = join(skillRoot, "SKILL.md");
    const source = await readFile(skillPath, "utf8");
    const skill = readSkillFrontmatter(source, skillPath);

    if (names.has(skill.name)) {
      throw new Error(`Duplicate skill name: ${skill.name}`);
    }

    names.add(skill.name);
    skills.push({ ...skill, codex: await readCodexSkill(skillRoot) });
  }

  return skills;
}

/**
 * Codex ignores Claude's `disable-model-invocation` frontmatter and reads
 * `agents/openai.yaml` instead. Returns undefined when the skill ships no
 * yaml, which leaves Codex free to fire it and shows the SKILL.md description.
 */
async function readCodexSkill(skillRoot) {
  let source;

  try {
    source = await readFile(join(skillRoot, "agents", "openai.yaml"), "utf8");
  } catch (error) {
    if (error.code === "ENOENT") {
      return undefined;
    }
    throw error;
  }

  const lines = source.split(/\r?\n/).map((line) => line.trim());
  const booleans = { false: false, true: true };

  return {
    implicitInvocation: booleans[readScalar(lines, "allow_implicit_invocation")],
    shortDescription: readScalar(lines, "short_description") || undefined,
  };
}

export async function collectSkills(skillsRoot) {
  const skills = [];
  const names = new Set();

  async function walk(directory) {
    let entries;

    try {
      entries = await readdir(directory, { withFileTypes: true });
    } catch (error) {
      if (error.code === "ENOENT") {
        return;
      }
      throw error;
    }

    for (const entry of entries) {
      const path = join(directory, entry.name);

      if (entry.isDirectory()) {
        await walk(path);
        continue;
      }

      if (entry.name !== "SKILL.md") {
        continue;
      }

      const source = await readFile(path, "utf8");
      const skill = readSkillFrontmatter(source, path);

      if (names.has(skill.name)) {
        throw new Error(`Duplicate skill name: ${skill.name}`);
      }

      names.add(skill.name);
      skills.push(skill);
    }
  }

  await walk(skillsRoot);
  return skills;
}

function readSkillFrontmatter(source, skillPath) {
  const match = source.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/);

  if (!match) {
    throw new Error(`Missing frontmatter: ${skillPath}`);
  }

  const lines = match[1].split(/\r?\n/);
  const name = readScalar(lines, "name");
  const description = readScalar(lines, "description").replace(/\s+/g, " ");
  const disableModelInvocation =
    readScalar(lines, "disable-model-invocation") === "true";

  if (!name || !description) {
    throw new Error(`Skill needs name and description: ${skillPath}`);
  }

  return { description, disableModelInvocation, name };
}

function readScalar(lines, key) {
  const index = lines.findIndex((line) => line.startsWith(`${key}:`));

  if (index === -1) {
    return "";
  }

  const rawValue = lines[index].slice(key.length + 1).trim();

  if (rawValue === "|" || rawValue === ">") {
    const block = [];

    for (const line of lines.slice(index + 1)) {
      if (line && !/^\s/.test(line)) {
        break;
      }
      block.push(line.trim());
    }

    return block.join(rawValue === ">" ? " " : "\n").trim();
  }

  if (rawValue.startsWith('"') && rawValue.endsWith('"')) {
    return JSON.parse(rawValue);
  }

  if (rawValue.startsWith("'") && rawValue.endsWith("'")) {
    return rawValue.slice(1, -1).replace(/''/g, "'");
  }

  return rawValue;
}

function parseArguments(arguments_) {
  const options = {};

  for (let index = 0; index < arguments_.length; index += 1) {
    const argument = arguments_[index];

    if (argument === "--check") {
      options.check = true;
      continue;
    }

    throw new Error(`Unknown argument: ${argument}`);
  }

  return options;
}

async function main() {
  const options = parseArguments(process.argv.slice(2));
  const result = await generateAdapters(options);

  if (options.check && result.drift.length > 0) {
    console.error(
      `Generated adapters have drift:\n${result.drift.map((path) => `- ${path}`).join("\n")}`,
    );
    process.exitCode = 1;
    return;
  }

  console.log(
    options.check ? "Generated adapters are current." : "Generated adapters updated.",
  );
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href
) {
  await main();
}
